GET http://localhost:5000/api/kai'sa/min-card

###
GET http://localhost:5000/api/asdfg/min-card

###
GET http://localhost:5000/api/Akshan/lore

###
GET http://localhost:5000/api/Akshan/spells

###
GET http://localhost:5000/api/Akshan/skins

###
GET http://localhost:5000/api/Akshan/overview

###
GET http://localhost:5000/api/champions/list

###
GET http://localhost:5000/api/champions/page/1/size/16

###
GET http://localhost:5000/api/Kai'sa/lore

###
GET http://localhost:5000/api/Kai'sa/spells

###
GET http://localhost:5000/api/Kai'sa/skins

###
GET http://localhost:5000/api/Kai'sa/overview