GET http://localhost:5000/api/Akshan/min-card

###
GET http://localhost:5000/api/Akshan/lore

###
GET http://localhost:5000/api/Akshan/spells

###
GET http://localhost:5000/api/Akshan/skins

###
GET http://localhost:5000/api/Akshan/overview
